# ETS 2 : Graphes

In [4]:
import numpy as np
m =[
    [0,1,0,0,0,1],
    [0,0,1,1,0,1],
    [0,1,0,0,1,0],
    [0,0,0,0,0,0],
    [1,1,0,1,0,1],
    [0,0,0,0,1,0]
]
M = np.array(m)
M = np.linalg.matrix_power(M,3)
print(M)

[[1 2 0 1 2 1]
 [2 2 1 3 0 3]
 [0 2 1 1 3 2]
 [0 0 0 0 0 0]
 [1 2 1 2 3 2]
 [0 1 1 1 1 2]]


## Ressources
    Programmation en Python pour les mathématiques Cours et exercices Ed 2 Pages 238-243
    Programmation en Python pour les mathématiques Cours et exercices Ed 2 Pages 170 à 178

## Représentation par liste d'adjacence

In [36]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
# (C) Alexandre Casamayou-Boucau, Pascal Chauvin, Guillaume Connan     #
#                                                                      #
# Complément de l'ouvrage :                                            #
# Programmation en Python pour les mathématiques                       #
# Editeur : Dunod                   -        Collection : Sciences Sup #
# ISBN-13: 978-2100738311           -                  Licence : GPLv2 #
########################################################################



class graphe(object):

	def __init__(self, liste_adj =None):
		"""  """
		self.__liste_adj = liste_adj



	def __str__(self):
		"""  """
		return str(self.__liste_adj)



	def adjacents(self, a):
		"""  """
		if self.__liste_adj is not None:
			if a in self.__liste_adj.keys():
				return self.__liste_adj[a]
		return []



	def est_adjacent(self, a, b):
		"""  """
		return (b in self.adjacents(a))



	def liste_adjacence(self):
		"""  """
		return self.__liste_adj



	def sommets(self):
		"""  """
		if self.__liste_adj is None:
			return []
		else:
			t = list(self.__liste_adj.keys())
			t.sort()
			return t



	def degre(self):
		"""  """
		return len(self.__liste_adj)



	def composante_connexe(self, s):
		"""  """
		p = []
		if s in self.sommets():
			q = []
			q.append(s)
			visite = []
			visite.append(s)
			while len(q) > 0:
				x = q.pop(0)
				p.append(x)
				for t in self.adjacents(x):
					if t not in visite:
						q.append(t)
						visite.append(t)
		p.sort()
		return p



	def composantes(self):
		"""  """
		c = []
		for s in self.sommets():
			t = self.composante_connexe(s)
			t.sort()
			if t not in c:
				c.append(t)
		return c



	def liaison(self, a, b):
		"""  """
		return (b in self.composante_connexe(a))
			


	def chaines(self, a, b):
		"""  """
		ll = []
		ll.append([a])
		while not arret(ll, b):
			q = []
			for p in ll:
				u = p[-1]
				if u == b:
					q.append(p)
				else:
					s = self.adjacents(u)
					for t in s:
						if not (t in p):
							v = [i for i in p]
							v.append(t)
							q.append(v)
			ll = q
		return ll



	def recherche_chaines(self, a, b):
		"""  """
		p = []
		if a != b and self.liaison(a, b):
			p = self.chaines(a, b)
		return p



def arret(liste, s):
	"""  """
	for item in liste:
		if item[-1] is not s:
			return False
	return True



In [37]:
def test1():
	print("----- test 1 -----")
	g = graphe(
		{
			'1': ['2', '3', '4'], 
			'2': ['1', '3'], 
			'3': ['1', '2', '4'], 
			'4': ['1', '3']
		}
	)

	for c in g.recherche_chaines('1', '3'):
		print(c)

	for c in g.recherche_chaines('1', '2'):
		print(c)

In [38]:
test1()

----- test 1 -----
['1', '2', '3']
['1', '3']
['1', '4', '3']
['1', '2']
['1', '3', '2']
['1', '4', '3', '2']


In [39]:
def test2():
	print("----- test 2 -----")
	g = graphe(
		{
			'A': ['B', 'D'], 
			'B': ['A', 'C', 'D', 'E', 'F'], 
			'C': ['B', 'F'], 
			'D': ['A', 'B', 'E'], 
			'E': ['B', 'D', 'F'], 
			'F': ['B', 'C', 'E'], 
			'G': ['H'], 
			'H': ['G']
		}
	)

#	print(g)

#	for k in g.sommets():
#		print(k, ":", g.adjacents(k))

	for c in g.recherche_chaines('A', 'F'):
		print(c)

#	print()

#	for c in g.recherche_chaines('F', 'A'):
#		print(c)

#	for c in g.recherche_chaines('G', 'H'):
#		print(c)

In [40]:
test2()

----- test 2 -----
['A', 'B', 'C', 'F']
['A', 'B', 'D', 'E', 'F']
['A', 'B', 'E', 'F']
['A', 'B', 'F']
['A', 'D', 'B', 'C', 'F']
['A', 'D', 'B', 'E', 'F']
['A', 'D', 'B', 'F']
['A', 'D', 'E', 'B', 'C', 'F']
['A', 'D', 'E', 'B', 'F']
['A', 'D', 'E', 'F']


## Algo Dijkstra

In [3]:
from queue import PriorityQueue

class Graph:
    
    def __init__(self, num_of_vertices):
        self.v = num_of_vertices
        self.edges = [[-1 for i in range(num_of_vertices)] for j in range(num_of_vertices)]
        self.visited = []
        
    def add_edge(self, u, v, weight):
        self.edges[u][v] = weight
        self.edges[v][u] = weight

In [4]:
def dijkstra(graph, start_vertex):
    D = {v:float('inf') for v in range(graph.v)}
    D[start_vertex] = 0

    pq = PriorityQueue()
    pq.put((0, start_vertex))

    while not pq.empty():
        (dist, current_vertex) = pq.get()
        graph.visited.append(current_vertex)

        for neighbor in range(graph.v):
            if graph.edges[current_vertex][neighbor] != -1:
                distance = graph.edges[current_vertex][neighbor]
                if neighbor not in graph.visited:
                    old_cost = D[neighbor]
                    new_cost = D[current_vertex] + distance
                    if new_cost < old_cost:
                        pq.put((new_cost, neighbor))
                        D[neighbor] = new_cost
    return D

## Test the dijkstra algo

![Image](test3.png "a title")

In [5]:

def test3():

    g = Graph(4)
    g.add_edge(0, 1, 2)
    g.add_edge(0, 2, 5)
    g.add_edge(1, 0, 3)
    g.add_edge(1, 2, 4)
    g.add_edge(1, 3, 8)
    g.add_edge(2, 1, 3)
    g.add_edge(2, 3, 7)
    g.add_edge(3, 2, 1)
    g.add_edge(3, 0, 2)
    
   
    
    
    D = dijkstra(g, 0)
    print(D)
    #Or, we could format it a bit more nicely:
    for vertex in range(len(D)):
        print("Distance from vertex 0 to vertex", vertex, "is", D[vertex])

In [6]:
test3()

{0: 0, 1: 3, 2: 3, 3: 2}
Distance from vertex 0 to vertex 0 is 0
Distance from vertex 0 to vertex 1 is 3
Distance from vertex 0 to vertex 2 is 3
Distance from vertex 0 to vertex 3 is 2
